name: build

on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-linux-musl
          - arm-linux-musleabihf
          - aarch64-linux-musl

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.10.0
      - name: Build
        working-directory: rsmb/src
        env:
          CC: zig cc --target=${{ matrix.target }} ${{ matrix.target == 'arm-linux-musleabihf' && '-mcpu=arm1136jf_s' || '' }}
        run: make broker_mqtts
      - name: Upload Binary
        uses: actions/upload-artifact@v3
        with:
          name: rsmb-${{ matrix.target }}
          path: rsmb/src/broker_mqtts

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Dowload Binaries
        uses: actions/download-artifact@v3
      - name: Rename Binaries
        run: |
          for file in $(find -name broker_mqtts)
          do
            new_file="${file%%-linux*}"
            mv -v "$file" "$new_file"
            rmdir -v "${file%/*}"
            sha256sum "$new_file" | tee "$new_file".sha256
          done
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*"
